  [31morigin/2.5.4[m
  [31morigin/2.5.5[m
  [31morigin/2.5.6[m
  [31morigin/2.5.7[m
  [31morigin/2.6.0[m
  [31morigin/2.6.1[m
  [31morigin/2.6.2[m
  [31morigin/2.6.4[m
  [31morigin/2.6.5[m
  [31morigin/2.6.6[m
  [31morigin/2.x[m
  [31morigin/HEAD[m -> origin/2.x
  [31mupstream/1.1.x[m
  [31mupstream/1.2.x[m
  [31mupstream/1.3.x[m
  [31mupstream/2.x[m
  [31mupstream/2.x-form-input-width-variable[m
  [31mupstream/2.x-remove-regulatoryinspector[m
  [31mupstream/HEAD[m -> upstream/2.x
  [31mupstream/allow-client-searchable-text-adapter-extensions[m
  [31mupstream/analysis-permissions-and-workflow[m
  [31mupstream/cannot-login-to-upgrade[m
  [31mupstream/contact-to-dx[m
  [31mupstream/deactivate-reindex-workflow-variables-patch-2593[m
  [31mupstream/dx-analysis[m
  [31mupstream/dx-analysis-service[m
  [31mupstream/dx-calculations[m
  [31mupstream/feature/dispatch-lock-analyses[m
  [31mupstream/feature/orphan-partitions[m
  [31mupstream/fix-autoimport-override-forward[m
  [31mupstream/fix-cannot-remove-partitions[m
  [31mupstream/fix-detection-limit-flush-on-submit[m
  [31mupstream/fix-display-view[m
  [31mupstream/fix-github-workflow[m
  [31mupstream/fix-jsonapi-import[m
  [31mupstream/fix-twitter-together[m
  [31mupstream/fix-ws-template-js-error[m
  [31mupstream/fix/auditlog-diff-precise[m
  [31mupstream/fix/calculation-msgid-collision[m
  [31mupstream/fix_calc_validator_AS_length[m
  [31mupstream/heartbeat[m
  [31mupstream/manually-rename-sample[m
  [31mupstream/master[m
  [31mupstream/multi-analyses[m
  [31mupstream/new-tweet[m
  [31mupstream/orphans-on-uidcatalog-clean[m
  [31mupstream/pin-plumber-version[m
  [31mupstream/port-clients[m
  [31mupstream/refactor/auditlog-to-senaite-core[m
  [31mupstream/remove-samplepointtitle-column-index[m
  [31mupstream/uncatalog-brain[m
  [31mupstream/validate-no-future-no-pst-1.3x[m
  [31mupstream/validate-volume[m
